#!/bin/python3

# Script d'interface entre INGInious et l'exercice modules_makefile
# Auteur: François De Keersmaeker
# Licence: GPLv3

import subprocess, shlex, os
from inginious import feedback, rst, input

# Switch working directory to student/
os.chdir("student")

# Global score
score = 0
feedback_str = ""

# Fetch and save the student code into a file for compilation
input.parse_template("Makefile.tpl", "Makefile")

# Compilation
p = subprocess.Popen(shlex.split("make"), stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
make_output = p.communicate()[0].decode('utf-8')

# Check compilation
if p.returncode:
    # Compilation failed
    feedback_str = "La compilation a échoué. La sortie de la commande ``make`` est la suivante:" + rst.get_codeblock('', make_output)
elif os.path.exists("prog"):
    # make builds the correct exec
    score += 50
    feedback_str = "La commande ``make`` produit le bon exécutable.\n\n"
    # Expected program output
    expected_output = "Bonjour\nHello\nCoucou (a = 0; b = 0)\nSalut\nCoucou (a = 1; b = 0)\n"
    # Run program to check output
    p = subprocess.Popen(shlex.split("./prog"), stderr=subprocess.STDOUT, stdout=subprocess.PIPE)
    prog_output = p.communicate()[0].decode('utf-8')
    if prog_output == expected_output:
        # Correct output
        score += 50
        feedback_str += "L'exécution du programme est correcte."
    else:
        # Wrong output
        feedback_str += "L'exécution du programme est incorrecte."
else:
    feedback_str = "La commande ``make`` ne produit pas le bon exécutable."

# Set score and feedback
feedback.set_problem_result("success" if score >= 100 else "failed", "makefile")
feedback.set_problem_feedback(feedback_str, "makefile")

# Remove source files
subprocess.run("rm -rf Makefile *.c *.tpl *.h *.o", shell=True)

# Set global score
feedback.set_grade(score)
feedback.set_global_result("success" if score >= 100 else "failed")
feedback.set_global_feedback("Bien joué ! Vous maîtrisez les Makefiles avec plusieurs modules." if score >= 100 else "Le Makefile n'est pas correct.")
